"===== General Settings =====
"
filetype plugin indent on
set nocompatible
syntax on

set exrc " If there's vimrc inside dir, source that
set noerrorbells
set expandtab
set shiftwidth=2
set tabstop=2
set colorcolumn=84
set smarttab
set autoindent
set smartindent

" Search
set incsearch
set hlsearch
set lazyredraw
set showmatch
set mat=2

set hidden
set signcolumn=yes
set number relativenumber
set encoding=utf-8
set ignorecase
set smartcase
set wildmode=longest:full,full
set nowrap
set list
set listchars=tab:»\ ,trail:·
set scrolloff=6
set sidescrolloff=6
set backspace=2 " make backspace delete indent,eol,start

" other
set updatetime=1000
set redrawtime=5000
set noswapfile
set nobackup
set nowritebackup
set shortmess+=c

"===== Keymaps =====
"
let mapleader = "\\"

nmap <leader>ve :e $MYVIMRC<CR>
nmap <leader>vr :source $MYVIMRC<CR>
map <C-c> <Esc>
nmap <leader><Space> :nohlsearch<CR>

map gf :edit <cfile><CR>

" Reselect visual after indenting
vnoremap < <gv
vnoremap > >gv

" Insert mode shortcut
imap ;; <Esc>A;<Esc>

nnoremap B ^
nnoremap E $

" Gui mode
"
set guifont=consolas:h11
set novisualbell
set lines=28
set columns=100
set t_Co=256
set ttyfast
set showmode
set showcmd

if has('termguicolor')
  set termguicolors
endif

" ===== Plugins =====
"
call plug#begin()
source ~/.vim/plugins/surround.vim
source ~/.vim/plugins/commentary.vim
source ~/.vim/plugins/vim-repeat.vim
source ~/.vim/plugins/emmet.vim
source ~/.vim/plugins/quick-scope.vim
source ~/.vim/plugins/lightline.vim
source ~/.vim/plugins/fzf.vim

if has('nvim')
  source ~/.vim/nvim.vim
endif

" Colorscheme of choice
source ~/.vim/plugins/dracula.vim
call plug#end()

doautocmd User PlugLoaded
